// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using IGRSS.BusinessLogicLayer;
using IGRSS.DataAccessLayer;
namespace IgrssTest
{
    /// <summary>
    ///This is a test class for IGRSS.BusinessLogicLayer.LicenseRenewal and is intended
    ///to contain all IGRSS.BusinessLogicLayer.LicenseRenewal Unit Tests
    ///</summary>
    [TestClass()]
    public class LicenseRenewalTest
    {


        private TestContext testContextInstance;

        /// <summary>
        ///Gets or sets the test context which provides
        ///information about and functionality for the current test run.
        ///</summary>
        public TestContext TestContext
        {
            get
            {
                return testContextInstance;
            }
            set
            {
                testContextInstance = value;
            }
        }
        #region Additional test attributes
        // 
        //You can use the following additional attributes as you write your tests:
        //
        //Use ClassInitialize to run code before running the first test in the class
        //
        //[ClassInitialize()]
        //public static void MyClassInitialize(TestContext testContext)
        //{
        //}
        //
        //Use ClassCleanup to run code after all tests in a class have run
        //
        //[ClassCleanup()]
        //public static void MyClassCleanup()
        //{
        //}
        //
        //Use TestInitialize to run code before running each test
        //
        //[TestInitialize()]
        //public void MyTestInitialize()
        //{
        //}
        //
        //Use TestCleanup to run code after each test has run
        //
        //[TestCleanup()]
        //public void MyTestCleanup()
        //{
        //}
        //
        #endregion


        /// <summary>
        ///A test for GetRenewalHistry (string)
        ///</summary>
        [TestMethod()]
        public void GetRenewalHistryTest()
        {
            IGRSS.BusinessLogicLayer.LicenseRenewal target =new  IGRSS.BusinessLogicLayer.LicenseRenewal();
            string LicenseNo ="pop345";
            Assert.IsInstanceOfType(target.GetRenewalHistry(LicenseNo), typeof(IGRSS.DataAccessLayer.LicenseReNewal.RenewLicenseDataTable), "IGRSS.BusinessLogicLayer.LicenseRenewal.GetRenewalHistry did not return the expec" +
                    "ted value.");
            
        }

        /// <summary>
        ///A test for GetRenewalHistryByLICID (Guid)
        ///</summary>
        [TestMethod()]
        public void GetRenewalHistryByLICIDTest()
        {
            IGRSS.BusinessLogicLayer.LicenseRenewal target =new  IGRSS.BusinessLogicLayer.LicenseRenewal();
            Guid LicenseApplicationId = new Guid("0bebd78a-40c6-4b34-9edf-6119c6a5b593"); // TODO: Initialize to an appropriate value
            Assert.IsInstanceOfType(target.GetRenewalHistryByLICID(LicenseApplicationId), typeof(IGRSS.DataAccessLayer.LicenseReNewal.RenewLicenseDataTable), "IGRSS.BusinessLogicLayer.LicenseRenewal.GetRenewalHistry did not return the expec" +
                    "ted value.");
        }

    }


}
